[package]
name = "pr-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
lru = "0.18.3"
parking_lot = "0.12.5"
pr-archive = { version = "0.1.0", path = "../pr-archive" }
pr-core = { version = "0.1.0", path = "../pr-core" }
pr-db = { version = "0.1.0", path = "../pr-db" }
pr-image = { version = "0.1.0", path = "../pr-image" }
pr-opds = { version = "0.1.0", path = "../pr-opds" }
pr-sync = { version = "0.1.0", path = "../pr-sync" }
pr-text = { version = "0.1.0", path = "../pr-text" }
rayon = "1.12.0"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
tokio = { version = "1.53.1", features = ["rt", "fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dev-dependencies]
image = "0.25.10"
zip = "8.6.0"
